language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start