language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install karma-cli -g
  - npm install
  - npm test
